blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/botframework
    about: The issue tracker is not for questions, please ask general "how-to" questions on Stack Overflow.