//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSkill.Tests.Utterances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlSettingsUtterances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlSettingsUtterances() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicSkill.Tests.Utterances.ControlSettingsUtterances", typeof(ControlSettingsUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicSkill.
        /// </summary>
        public static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i want to adjust the volume.
        /// </summary>
        public static string AdjustVolumn {
            get {
                return ResourceManager.GetString("AdjustVolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you turn the volume up please?.
        /// </summary>
        public static string AdjustVolumnUp {
            get {
                return ResourceManager.GetString("AdjustVolumnUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string DefaultVolumnDirection {
            get {
                return ResourceManager.GetString("DefaultVolumnDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you stop playing this song?.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you pause please?.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you please shuffle this playlist?.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
    }
}
