//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSkill.Tests.Utterances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayMusicDialogUtterances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayMusicDialogUtterances() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicSkill.Tests.Utterances.PlayMusicDialogUtterances", typeof(PlayMusicDialogUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for me.
        /// </summary>
        public static string DefaultAfterMusic {
            get {
                return ResourceManager.GetString("DefaultAfterMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1989.
        /// </summary>
        public static string DefaultAlbum {
            get {
                return ResourceManager.GetString("DefaultAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:album:37i9dQZF1DXcCnTAt8Cf.
        /// </summary>
        public static string DefaultAlbumUri {
            get {
                return ResourceManager.GetString("DefaultAlbumUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taylor swift.
        /// </summary>
        public static string DefaultArtist {
            get {
                return ResourceManager.GetString("DefaultArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:track:defaultArtistAndTrack.
        /// </summary>
        public static string DefaultArtistAndTrackUri {
            get {
                return ResourceManager.GetString("DefaultArtistAndTrackUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:artist:37i9dQZF1DXcCnTAt8Cf.
        /// </summary>
        public static string DefaultArtistUri {
            get {
                return ResourceManager.GetString("DefaultArtistUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could you please play.
        /// </summary>
        public static string DefaultBeforeMusic {
            get {
                return ResourceManager.GetString("DefaultBeforeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r&amp;b.
        /// </summary>
        public static string DefaultGenre {
            get {
                return ResourceManager.GetString("DefaultGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:track:defaultGenreAndArtist.
        /// </summary>
        public static string DefaultGenreAndArtistUri {
            get {
                return ResourceManager.GetString("DefaultGenreAndArtistUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:track:defaultGenre.
        /// </summary>
        public static string DefaultGenreUri {
            get {
                return ResourceManager.GetString("DefaultGenreUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string DefaultInBetweenMusic {
            get {
                return ResourceManager.GetString("DefaultInBetweenMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rock classic.
        /// </summary>
        public static string DefaultPlayList {
            get {
                return ResourceManager.GetString("DefaultPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:playlist:37i9dQZF1DXcCnTAt8Cf.
        /// </summary>
        public static string DefaultPlayListUri {
            get {
                return ResourceManager.GetString("DefaultPlayListUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shake it off.
        /// </summary>
        public static string DefaultTrack {
            get {
                return ResourceManager.GetString("DefaultTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:track:37i9dQZF1DXcCnTAt8Cf.
        /// </summary>
        public static string DefaultTrackUri {
            get {
                return ResourceManager.GetString("DefaultTrackUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotify:track:default.
        /// </summary>
        public static string DefaultUri {
            get {
                return ResourceManager.GetString("DefaultUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play music.
        /// </summary>
        public static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
    }
}
