name: PR Style

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  prStyle:
    name: pr-style
    runs-on: ubuntu-latest

    steps:
      - uses: joshgummersall/pr-style@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          require_issue: "true"
          title_prefixes: "build:, bump:, ci:, chore:, docs:, feat:, fix:, port:, refactor:"